### ISSUE TITLE
When used on a .Net Core Console app, a simple test throws exceptions on GetBytes()

### ISSUE THREAD

**Issue by SparkDustJoe** [kmaragon/Konscious.Security.Cryptography#3]
An unhandled exception of type 'System.AggregateException' occurred in System.Private.CoreLib.ni.dll

Additional information: One or more errors occurred.

Inner Exception: 
{System.DivideByZeroException: Attempted to divide by zero.
   at Konscious.Security.Cryptography.Argon2Core.<InitializeLanes>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Konscious.Security.Cryptography.Argon2Core.<Hash>d__27.MoveNext()}

Code:
            string testPwd = "B@ll0ck$";
            Guid salt = Guid.NewGuid();
            myArg = new Argon2d(UTF8Encoding.UTF8.GetBytes(testPwd));
            myArg.Salt = salt.ToByteArray();
            byte[] hashResult = myArg.GetBytes(32);  <----Thrown here
            Console.WriteLine(Convert.ToString(hashResult));
            Console.ReadKey(true);

**Comment by kmaragon** [comment]
What are the values for Iterations, MemorySize, and DegreeOfParallelism?

**Comment by kmaragon** [comment]
Fwiw an outstanding issue is that if any of these are 0 it won't throw an exception saying it can't be zero. Except sometimes in the form you describe. Which if that's what you're facing, sorry for the crappy user experience. I recently fixed a similar issue in the Blake2B library

**Comment by SparkDustJoe** [comment]
I didn't initialize those thinking that they had defaults, I can try
setting those and checking again tomorrow.  And as a fellow developer, I've
been bitten countless times by the "Wait, he did what?" errors from users
finding new and exciting ways to break my code.  :) All part of the process.

**Comment by kmaragon** [comment]
Yeah - that'd probably be it. There are no sensible defaults because sensible totally is subjective and entirely dependent on the use case. But there's also no "InvalidOperationException { Message: You can't hash data with 0 iterations using 0 memory and 0 threads. }" which there should be. And I will add that in the next package release. It's all in the docs but asking someone to go read the docs (when the nuget package is right there and the package is essentially just two visible classes) is really crummy. A simple exception would have been better. Sorry it wasn't there in this case.

**Comment by kmaragon** [comment]
With the latest package, you should get an exception that is informative rather than divide by 0. Let me know if that works out better.

**Comment by SparkDustJoe** [comment]
MUCH better :+1:  :-)  I'll close out this issue and bang against it more.
