### ISSUE TITLE
Is this library still actively maintained? 

### ISSUE THREAD

**Issue by Insomniak47** [kmaragon/Konscious.Security.Cryptography#48]
Hey All, 

Just checking in before I make a PR but is this lib still maintained? It seems like the last set of changes was a number of years ago. Is this lib still the blessed dotnet implementation of the Argon algos? 

I've got a few perf changes that I have to clean up and get in but I just want to make sure the lib is still maintained before I start at that. 

All the best,
Chris

I've got a few things that I'd like to contrib if possible (I can split them into separate issues if that's useful)
- Removing Unsafe code
- Performance/memory allocation improvements
- Performance suite

**Comment by ezekielnewren** [comment]
I can't speak for the author, but I'd like to use this library. I need it to work with .NETFramework,Version=v4.0 because I'm adding a feature to [KeeAgent](https://github.com/dlech/KeeAgent) that will allow it to read PPKv3 files, and it requires Argon2.

**Comment by keef-cognitiv** [comment]
It's on break at the moment. I'm crushed under the weight of life at the moment. I expect to have some semblance of a normal life in late 2022 to start getting to some things in this lib. But first and foremost, a perf suite would be so incredibly welcome. So I'd definitely like to see that first.

I was looking forward to doing some perf updates when I have a life again. I think the tooling for Linux has drastically improved since I last had any time to work on this. But as long as said perf suite justifies any perf changes, they're very welcome.

**Comment by kmaragon** [comment]
It's on break at the moment. I'm crushed under the weight of life at the moment. I expect to have some semblance of a normal life in late 2022 to start getting to some things in this lib. But first and foremost, a perf suite would be so incredibly welcome. So I'd definitely like to see that first.

I was looking forward to doing some perf updates when I have a life again. I think the tooling for Linux has drastically improved since I last had any time to work on this. But as long as said perf suite justifies any perf changes, they're very welcome.

**Comment by Insomniak47** [comment]
@kmaragon I'll have to port some of my changes over from a fork we made internally (in order to leverage some of the memory features). 

I should, however be able to bring a perf suite over (and I also have a test harness that runs it against the python impl to ensure I haven't broken anything)
