### ISSUE TITLE
Official Release offers Argon2d, Argon2i, and new hybrid "id"

### ISSUE THREAD

**Issue by SparkDustJoe** [kmaragon/Konscious.Security.Cryptography#7]
Will that hybrid be supported in this codebase?

https://github.com/P-H-C/phc-winner-argon2/commit/a664086ca95ea5d9168a60baa5da3a5f4ac34801
https://github.com/P-H-C/phc-winner-argon2/releases/tag/20161029

Thanks

**Comment by kmaragon** [comment]
The answer is yes... but when is a major question. Aside from the timing, I need to go reread the doc to see what the updates are. I expect to start soon but I don't know when it will be done. My higher priority is to do some optimization work. But I am kind of waiting for:

https://github.com/dotnet/coreclr/issues/445

So I can get a reliable profiler up on Linux to do the optimization. The main reason that I am prioritizing that is so that I don't have more code that needs rework / optimization once I have an idea of where I can optimize. I did some crappy SIMD optimization already but I don't actually even know if that's better than the vectorized version, since there's some overhead to arranging the data in memory to be vectorizable. A profiler would help me figure that out.

**Comment by SparkDustJoe** [comment]
That post has had a lot of comments and new issues spawn from it, so they are definitely working on it, but it looks like Fall of this year will be the target release for *nix.

**Comment by kmaragon** [comment]
This is really old. But I wanted to add a comment that I have a local branch with this implemented. But I have the overhead to start generating test cases with the reference implementation and write the tests to verify what I have. But if I manage a couple of days off of work, I think I'll have this soon... assuming it ends up being as trivial as it turns out to have seemed.

**Comment by ffMathy** [comment]
Please keep us updated!

**Comment by flacidsnake** [comment]
Any news regarding this?

Thank you

**Comment by johnnyRose** [comment]
+1, would love to see this when you have a chance.

**Comment by kmaragon** [comment]
Sorry for the delay on this - I just opened the PR with Argon2id support for myself to review :stuck_out_tongue: 

But really it's to just run it through CI. I'll publish the package tomorrow (1/4/2019) assuming all goes well there.

**Comment by kmaragon** [comment]
15 minutes later - it's uploaded. I forgot how much faster C# packages are than C++ packages.

**Comment by johnnyRose** [comment]
Thanks a lot, @kmaragon!
